board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path("list/", views.BoardListView.as_view(), name="board_list"),
    path("write/", views.BoardWriteView.as_view(), name="board_write"),
    path("detail/<int:pk>/", views.BoardDetailView.as_view(), name="board_detail"),
    path("delete/<int:pk>/", views.BoardDeleteView.as_view(), name="board_delete"),
    path("update/<int:pk>/", views.BoardUpdateView.as_view(), name="board_update"),
    path("like/<int:pk>/", views.LikesView.as_view(), name="board_like"),
    path("comment/write", views.CommentWriteView.as_view(), name="comment_write"),
    path("comment/delete/<int:pk>", views.CommentDeleteView.as_view(), name="comment_delete"),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Favicon-->    
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'default/assets/favicon.ico' %}"
    />
    
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"
    />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      rel="stylesheet"
      href="//unpkg.com/bootstrap@4/dist/css/bootstrap.min.css"
    />

    <script src="//unpkg.com/jquery@3/dist/jquery.min.js"></script>
    <script src="//unpkg.com/popper.js@1/dist/umd/popper.min.js"></script>
    <script src="//unpkg.com/bootstrap@4/dist/js/bootstrap.min.js"></script>

    <script src="{% static 'default/js/default.js' %}"></script>

    {% block head %} {% endblock %}
    {% block meta %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include "header.html" %}
    {% block main %} {% endblock %}
    {% include "footer.html" %}
    {% block script %} {% endblock %}
  </body>
</html>

templates/board_detail.html
{% extends "base.html" %}
{% block head %}
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
{% endblock %}
{% block main %}
<div class="container my-5">
    <header class="jumbotron my-1">
        <h1 class="display-4">The current user needs to be logged in to write.</h1>
        <p class="lead">
            A tag has many to many relationship in a board table.
        </p>  
    </header>
    <div class="text-center text-danger">{{ err_msg }}</div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" id="title" value="{{ board.title }}" readonly />
            <label for="contents">내용</label>
            <textarea class="form-control" readonly>{{ board.contents }}</textarea>
            <label for="tags">태그</label>
            <span id="tags" class="form-control">
                {{ board.tags.all|join:", " }}
            </span>
            <div class="my-4">
            {% if request.user in article.like_users.all %}
            <a href="{% url 'board:board_like' board.id %}">
                <i class="fas fa-heart fa-lg animated hinge delay-1s" style="color: red;"></i>
            </a>
            {% else %}
            <a href="{% url 'board:board_like' board.id %}">
                <i class="far fa-heart fa-lg animated infinite bounce delay-1s" style="color: gray;"></i>
            </a>
            {% endif %}
            <p class="mt-1">{{ board.like_count }}명이 좋아합니다.</p>
            </div>

            {% if board.photo %}
            <label for="title">사진</label><br>
            <img src="{{ board.photo.url }}" style="max-width:40%;"/>
            {% endif %}
            </div>
            <button class="btn btn-primary" onclick="location.href='/board/list/'">돌아가기</button>
            <button class="btn btn-primary ml-3" onclick="location.href='{% url 'board:board_update' board.id %}'">수정하기</button>
            <button class="btn btn-primary ml-3" onclick="location.href='{% url 'board:board_delete' board.id %}'">삭제하기</button>
            
        </div>
    </div>

    <!-- 댓글 목록 -->
    
    <div class="row mx-2">
        <div class="col-lg-10 comment-bg">
            <div class="page-header my-2">
                <h2>Comments</h2>
            </div>
            <div class="comments-list">
            {% for comment in comments %}
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading user_name">
                        {{ comment.user }}
                        </h4>
                        {{ comment.content }}
                        <hr>
                    </div>
                    <button class="btn btn-secondary btn-sm ml-3" onclick="location.href='{% url 'board:comment_delete' comment.id %}'">삭제하기</button>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

    <!-- 댓글 등록하기 -->
    <div class="row mx-2">
        {% if cmt_errors %}
        <ul>
            {% for error in cmt_errors %}
            <li><div class="alert alert-primary">{{ error }}</div></li>
            {% endfor %}
        </ul>
        {% endif %}
        <h3>댓글 쓰기</h3>
        <form method="post" action="{% url 'board:comment_write' %}" enctype="multipart/form-data" class="col-lg-12 mx-auto">
        {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ board.id }}">
            <div class="form-group row">
                <textarea class="form-control" name="content" rows="7"></textarea>
            </div>
        <div class="form-group row float-right">
            <button type="submit" class="btn btn-primary">저장하기</button>
        </div>
        </form>
    </div>
</div>
{% endblock %}

templates/board_list.html
{% extends "base.html" %}

{% block main %}
<div class="container my-5">
    <header class="jumbotron my-1">
        <h1 class="display-4">The current user needs to be logged in to write.</h1>
        <p class="lead">
            A tag has many to many relationship in a board table.
        </p>  
    </header>
    <div class="row">
        <div class="col-12">
            <table class="table table-light">
            <thead class="thead-light">
                <tr>
                <th>#</th>
                <th>제목</th>
                <th>좋아요</th>
                <th>아이디</th>
                <th>일시</th>
                </tr>
            </thead>
            <tbody class="text-dark">
                {% for board in boards %}
                <tr onclick="location.href='/board/detail/{{ board.id }}/'">
                <th>{{ board.id }}</th>
                <td>{{ board.title }}</td>
                <td>{{ board.like_count }}</td>
                <td>{{ board.writer }}</td>
                <td>{{ board.registered_dttm }}</td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <nav>
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전으로</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                <a class="page-link" href="#">이전으로</a>
                </li>
                {% endif %}
                <li class="page-item active">
                <a class="page-link" href="#">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</a>
                </li>
                {% if page_obj.has_next %}
                <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음으로</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                <a class="page-link disabled" href="#">다음으로</a>
                </li>
                {% endif %}
            </ul>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <button class="btn btn-primary" onclick="location.href='/board/write/'">글쓰기</button>
        </div>
    </div>
</div>
{% endblock %}

templates/board_update.html
{% extends "base.html" %} 
{% block main %}
<div class="container my-5">
    <header class="jumbotron my-1">
        <h1 class="display-4">The current user needs to be logged in to write.</h1>
        <p class="lead">
            A tag has many to many relationship in a board table.
        </p>  
    </header>
    <div class="text-center text-danger">{{ err_msg }}</div>
    <div class="row">
    <div class="col-12">
        <form method="POST" action="{% url 'board:board_update' board_key %}" enctype="multipart/form-data">
        {% csrf_token %}                
            <div class="form-group">                
                <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                <input class="form-control" id="{{ form.title.id_for_label }}" placeholder="{{ form.title.label }}" name="{{ form.title.name }}" value="{{ form.title.value }}"/>
                <label for="{{ form.contents.id_for_label }}">{{ form.contents.label }}</label>
                <textarea type="{{ form.contents.form.widget.input_type }}" class="form-control h-25" rows="10" name="{{ form.contents.name }}" placeholder="{{ form.contents.label }}" value="{{ form.contents.value }}">{{ form.contents.value }}</textarea>                
                <label for="{{ form.tags.id_for_label }}">{{ form.tags.label }}</label>
                <input class="form-control" id="{{ form.tags.id_for_label }}" placeholder="{{ form.tags.label }}" name="{{ form.tags.name }}" value="{{ form.tags.value|join:', ' }}"/>
                {% if form.photo %}
                <label for="{{ form.photo.id_for_label }}">{{ form.photo.label }}</label>
                <input type="{{ form.photo.field.widget.input_type }}" class="form-control" id="{{ form.photo.id_for_label }}" placeholder="{{ form.photo.label }}" name="{{ form.photo.name }}" value="{{ form.photo.value }}"/>
                {% else %}
                <label for="{{ form.photo.id_for_label }}">{{ form.photo.label }}</label>
                <input type="{{ form.photo.field.widget.input_type }}" class="form-control" id="{{ form.photo.id_for_label }}" placeholder="{{ form.photo.label }}" name="{{ form.photo.name }}" value="{{ form.photo.value }}"/>
                {% endif %}
                {% if form.photo %}
                <img src="{{ form.photo.value.url }}" class="my-2" style="max-width:40%;"/>
                {% endif %}
            </div>            
            {% if form.title.errors or form.contents.errors %}
            <span style="color: red">{{ form.title.errors }}{{ form.contents.errors }}</span>
            {% endif %}        
            <button type="submit" class="btn btn-primary">수정하기</button>
            <button type="button" class="btn btn-primary" onclick="location.href='{% url 'board:board_detail' board_key %}'">돌아가기</button>
        </form>
    </div>
    </div>
</div>
{% endblock %}

templates/board_write.html
{% extends "base.html" %} 
{% block main %}
<div class="container my-5">
    <header class="jumbotron my-1">
        <h1 class="display-4">The current user needs to be logged in to write.</h1>
        <p class="lead">
            A tag has many to many relationship in a board table.
        </p>  
    </header>
    <div class="row">
    <div class="col-12">
        <form method="POST" action="{% url 'board:board_write' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% ifequal field.name 'contents' %}
            <textarea class="form-control h-25" rows="10" name="{{ field.name }}" placeholder="{{ field.label }}"></textarea>                      
            {% else %}            
            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
            placeholder="{{ field.label }}" name="{{ field.name }}" />
            {% endifequal %}
        </div>
        {% if field.errors %}
        <span style="color: red">{{ field.errors }}</span>
        {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-primary">글쓰기</button>
        <button type="button" class="btn btn-primary" onclick="location.href='/board/list/'">돌아가기</button>
        </form>
    </div>
    </div>
</div>
{% endblock %}

templates/footer.html
{% block footer %} 
<footer class="py-5 bg-dark">
    <div class="container">
    <p class="m-0 text-center text-white">Copyright © Your Website 2021</p>
    </div>
</footer>
{% endblock %}
{% block script %}
{% endblock %}

templates/header.html
{% block navigation %} 
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <a class="navbar-brand" href="{% url 'home:index' %}">Django function based web site</a>
    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarResponsive"
        aria-controls="navbarResponsive"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
        <li class="nav-item "><a class="nav-link" href="{% url 'home:index' %}">Home</a></li>        
        <li class="nav-item "><a class="nav-link" href="{% url 'user:register' %}">Register</a></li>
        <li class="nav-item "><a class="nav-link" href="{% url 'user:login' %}">Login</a></li>
        <li class="nav-item "><a class="nav-link" href="{% url 'user:logout' %}">Logout</a></li>        
        <li class="nav-item "><a class="nav-link" href="{% url 'board:board_list' %}">list</a></li>        
        <li class="nav-item "><a class="nav-link" href="{% url 'board:board_write' %}">write</a></li>       
        </ul>
    </div>
    </div>
</nav>
{% endblock %}

templates/index.html
{% extends "base.html" %} 
{% load static %}
{% block main %} 
<!-- Header-->
<header class="bg-primary py-5 mb-5">
<div class="container h-50">
    <div class="row h-50 align-items-center">
        <div class="col-lg-12">
        <h1 class="display-5 text-white mt-2 mb-2">
            Django function based web site
        </h1>
        <p class="lead mb-5 text-white-50">
            This site made to understand how to use django funtional programing.
            If you have any better idea to share with django beginner, join our github group.
        </p>
        <a class="btn btn-success btn-lg" href="#!">Join the github group</a>
        </div>
    </div>
</div>
</header>
<!-- Page Content-->
<div class="container">
    <!-- Jumbotron Header-->
    <header class="jumbotron my-4">

    {% if username %}
    <h1 class="display-4">Hello {{ username }}</h1>
    {% else %}
    <h1 class="display-4">Hello anonymous</h1>
    {% endif %}
    <p class="lead">
        User can write note after login.        
    </p>    
    </header>
    <!-- Page Features-->
    <div class="row text-center">
        {% for board in boards %}
        <div class="col-lg-4 col-md-6 mb-4">            
            <div class="card h-100">
                {% if board.photo_thumbnail %}       
                <img
                    class="card-img-top"                
                    src="{{ board.photo_thumbnail.url }}"
                    alt="{{ board.title }}"
                />
                {% else %}
                <img
                    class="card-img-top"                
                    src="{{ board.photo.url }}" 
                    alt="{{ board.title}} "
                />
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ board.title|truncatechars:20 }}</h5>
                    <p class="card-text">
                    {{ board.contents|truncatechars:20 }}
                    </p>
                </div>
                <div class="card-footer">
                    <p >{{ board.like_count }}명이 좋아합니다.</p>
                    <a class="btn btn-primary" href="/board/detail/{{ board.id }}/">Detail More!</a>
                </div>
            </div>            
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %} 
{% load static %} 
{% block main %}
<div id="login">
    <div class="container my-3">
        <header class="jumbotron my-1">
            <h1 class="display-4">Login using new user table</h1>
            <p class="lead">
                It doesn't use django's user model.
                Use the created new table by user.            
            </p>  
        </header>
        <div class="text-center text-danger">{{ error }}</div>
        <div class="text-center text-danger">
        {% if messages %}
            {% for message in messages %}
                {{ message.tags }}
                {{ message.message }}
            {% endfor %}
        {% endif %}
        {{ error }}
        </div>
        <br />
        <h3 class="text-center text-danger">Login</h3>
        <br />
        <hr />
        <div class="col-md-6 mx-auto">
            <form method="POST" action="{% url 'user:login' %}">
                {% csrf_token %} {% for field in form %}
                <div class="form-group">
                <label for="{{ field.id_for_label }}" class="text-danger"
                    >{{ field.label }}</label
                ><br />
                <input
                    type="{{ field.field.widget.input_type }}"
                    class="form-control"
                    id="{{ field.id_for_label }}"
                    placeholder="{{ field.label }}"
                    name="{{ field.name }}"
                    class="form-control"
                />
                </div>
                {% if field.errors %}
                <span style="color: red">{{ field.errors }}</span>
                {% endif %}
                {% if field.errors %}
                <span class="form-group" style="color: red">{{ field.errors }}</span>
                {% endif %} {% endfor %}
                <div class="form-group">
                <button type="submit" class="form-control btn btn-danger">
                    Submit
                </button>
                </div>
            </form>
            <div class="form-group">
                <button
                type="button"
                class="mt-1 form-control btn btn-danger"
                onclick="{% url 'user:register' %}"
                >
                Register
                </button>
            </div>
        </div>
  </div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load static %}
{% block main %}
<div class="register">
  <div class="container my-3">
    <header class="jumbotron my-1">
        <h1 class="display-4">Register using new user table</h1>
        <p class="lead">
            It doesn't use django's user model.
            Use the created new table by user.            
        </p>
    </header>
    <div class="text-center text-danger">{{ error }}</div>
    <br />
    <h3 class="text-center text-danger">Register</h3>
    <br />
    <hr />
    <div class="col-md-6 mx-auto">
      <form method="POST" action="{% url 'user:register' %}">
        {% csrf_token %}
         {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
              placeholder="{{ field.label }}" name="{{ field.name }}" />
          </div>
          {% if field.errors %}
          <span style="color: red">{{ field.errors }}</span>
          {% endif %}
          {% endfor %}
          <button type="submit" class="form-control btn btn-danger">
            Register
          </button>
      </form>
    </div>
  </div>
</div>

{% endblock %}